### ISSUE TITLE
How the fuck

### ISSUE THREAD

**Issue by marysiamzawka** [jbscj/lr2-memleak-fix#1]
Please provide documentation.
If an issue unresolved for 13 years is really fixable with one instruction swap I'm gonna flip

**Comment by jbscj** [comment]
It is stated that this patch only fixes the preview keysounds. To completely get rid of all memory leaks is next to impossible. However, the preview leak is known to be the worst one. Not releasing the keysounds can cause crashes in minutes. Other leaks definitely exist, but it might need hours for those to take effect.
